### ISSUE TITLE
Make dark mode persistent

### ISSUE THREAD

**Issue by fabienheureux** [kooparse/bast#4]
Well, title is pretty obvious.

Could be cool if dark mode was persistent, even accross sessions.
Maybe use a variable in the user settings in order to set it ?

**Comment by kooparse** [comment]
Yes! It is working while developing the project because my hack (from https://github.com/chakra-ui/chakra-ui/issues/349) works when using `Next` node server. I think that I could make it works pretty easily but you'd end up with a flashy white splash on refresh. 

I could also store a variable in the database, but it won't fix my white splash problem!
I'll try things this weekend! :)

**Comment by kooparse** [comment]
Ok, now it's persistent but we still have this white splash...
