### ISSUE TITLE
Roadmap for bast

### ISSUE THREAD

**Issue by schoenenberg** [kooparse/bast#85]
Hi,

this is a really cool project!! I was searching for website analytics using rust and found *bast*. So, thank you for sharing this with the open source community!

What are the future plans for *bast*? Do you have a roadmap?

Thanks!
Max

**Comment by kooparse** [comment]
Hi! Thanks! :-)

The current roadmap:

- Using `sqlx` instead of `diesel` (to bring async to database connections)
- Modify/Fix the *average time* metric (it's sometimes awkward)
- Add real unit tests (and testing the database on github actions) 
- Maybe clean the `server/controllers/collect.rs` file a bit
- Add geolocalisation 🙏 

Right now, I'm focusing on game development, so I am just maintaining this project (and I'm using it of course). But I would be more than happy to help if someone wants to participate in those "features"! ;)

**Comment by bacloud22** [comment]
Hi @schoenenberg fork it and take the lead.
